ALTER TABLE "students"
ADD COLUMN "email_sent" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "email_sent_at" TIMESTAMPTZ,
ADD COLUMN "email_status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
ADD COLUMN "email_retry_count" INTEGER NOT NULL DEFAULT 0;
